/**
 * Guide sidebars are generated by the documentation fetch workflows.
 * Missing generated files resolve to empty sidebars so fresh checkouts can boot
 * before the first generated-state restore.
 */

// @ts-check

const fs = require('node:fs')
const path = require('node:path')

function tryRequire(modulePath) {
  try {
    return require(modulePath)
  } catch {
    return []
  }
}

const applyOverrides = require('./config/applyOverrides')

function collectDocIds(items, ids = []) {
  for (const item of items || []) {
    if ((item.type === 'doc' || item.type === 'ref') && item.id) ids.push(item.id)
    if (item.link?.type === 'doc' && item.link.id) ids.push(item.link.id)
    if (Array.isArray(item.items)) collectDocIds(item.items, ids)
  }
  return ids
}

function hasTutorialDoc(id) {
  if (!id.startsWith('tutorials/')) return true
  const relative = id.slice('tutorials/'.length)
  const base = path.join(__dirname, 'docs', 'tutorials', ...relative.split('/'))
  return fs.existsSync(`${base}.md`) || fs.existsSync(`${base}.mdx`)
}

function loadGuidesSidebar() {
  const generated = applyOverrides(tryRequire('./config/generated/guides.sidebar'), require.resolve('./config/sidebar-overrides/guides.json'))
  if (generated.length > 0 && collectDocIds(generated).every(hasTutorialDoc)) return generated
  return [{ type: 'autogenerated', dirName: 'tutorials' }]
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: loadGuidesSidebar(),
  releasesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials/get-started/release-notes',
    },
  ],
}

module.exports = sidebars
