/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    onPremiseSidebar: [
        {
          type: 'category',
          label: '部署运维手册',
          link: {
            type: 'generated-index',
            title: '部署运维手册',
            description: '本手册关注 Milvus 私有化镜像的部署和日常运维等操作，包括 Milvus 集群安装、升级、配置变更、扩缩容和监控告警配置等章节。',
            slug: '/deployment-and-operations',
            keywords: ['部署', '运维', '私有化镜像', 'Milvus']
          },
          collapsible: false,
          items: [{ type: 'autogenerated', dirName: 'docs/ops'}]
        },
        // {
        //   type: 'category',
        //   label: 'vDB 使用手册',
        //   link: {
        //     type: 'generated-index',
        //     title: 'vDB 使用手册',
        //     description: '本手册关注 Milvus 集群的使用，包括基本概念、Collection 管理、数据插入与更新、向量搜索与查询等章节。',
        //     slug: '/user-guides',
        //     keywords: ['vDB', '使用手册', '私有化镜像', 'Milvus']
        //   },
        //   collapsible: false,
        //   items: [
        //     'docs/vdb/test',
        //   ]
        // }
    ],
  
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
  };
  
  module.exports = sidebars;