/**
 * Reference sidebars are generated by the documentation fetch workflows.
 * Missing generated files resolve to empty sidebars so fresh checkouts can boot
 * before the first generated-state restore.
 */

// @ts-check

function tryRequire(modulePath) {
  try {
    return require(modulePath)
  } catch {
    return []
  }
}

const applyOverrides = require('./config/applyOverrides')

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  pythonSidebar: applyOverrides(tryRequire('./config/generated/python.sidebar'), require.resolve('./config/sidebar-overrides/python.json')),
  javaSidebar: applyOverrides(tryRequire('./config/generated/java.sidebar'), require.resolve('./config/sidebar-overrides/java.json')),
  goSidebar: applyOverrides(tryRequire('./config/generated/go.sidebar'), require.resolve('./config/sidebar-overrides/go.json')),
  nodeSidebar: applyOverrides(tryRequire('./config/generated/node.sidebar'), require.resolve('./config/sidebar-overrides/node.json')),
  cliSidebar: applyOverrides(tryRequire('./config/generated/cli.sidebar'), require.resolve('./config/sidebar-overrides/cli.json')),
  restfulSidebar: applyOverrides(tryRequire('./config/generated/restful.sidebar'), require.resolve('./config/sidebar-overrides/restful.json')),
}

module.exports = sidebars
