/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // referenceSidebar: [{type: 'autogenerated', dirName: 'api'}],
    restfulSidebar: [{type: 'autogenerated', dirName: 'api/restful'}],
    pythonSidebar: [{type: 'autogenerated', dirName: 'api/python'}],
    javaSidebar: [{type: 'autogenerated', dirName: 'api/java'}],
    goSidebar: [{type: 'autogenerated', dirName: 'api/go'}],
    nodejsSidebar: [{type: 'autogenerated', dirName: 'api/nodejs'}],
  
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
  };
  
  module.exports = sidebars;