/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // referenceSidebar: [{type: 'autogenerated', dirName: 'api'}],
    // restfulSidebar: [{type: 'autogenerated', dirName: 'api/restful'}],
    restfulSidebar: [
      'api/restful/restful/overview',
      'api/restful/restful/versioning',
      {
        type: 'category',
        label: 'V2',
        link: { type: 'doc', id: 'api/restful/restful/v2/v2' },
        collapsible: false,
        items: [
          {
            type: 'category',
            label: 'Control Plane',
            link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/control-plane' },
            collapsed: false,
            items: [
              {
                type: 'category',
                label: 'Cloud Meta',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/cloud-meta-v2/cloud-meta-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/cloud-meta-v2" }]
              },
              {
                type: 'category',
                label: 'Cluster Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/cluster-operations-v2/cluster-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/cluster-operations-v2" }]
              },
              {
                type: 'category',
                label: 'Import Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/import-operations-v2/import-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/import-operations-v2" }]
              },
              {
                type: 'category',
                label: 'Cloud Migration',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/cloud-migration-v2/cloud-migration-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/cloud-migration-v2" }]
              },
              {
                type: 'category',
                label: 'Backup & Restore',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/backup-and-restore-v2/backup-and-restore-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/backup-and-restore-v2" }]
              },
              {
                type: 'category',
                label: 'Cloud Job',
                link: { type: 'doc', id: 'api/restful/restful/v2/control-plane/cloud-job-v2/cloud-job-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/control-plane/cloud-job-v2" }]
              }
            ]
          },
          {
            type: 'category',
            label: 'Data Plane',
            link: {type: 'doc', id: 'api/restful/restful/v2/data-plane/data-plane'},
            collapsed: false,
            items: [
              {
                type: 'category',
                label: 'Collection Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/collection-operations-v2/collection-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/collection-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'Index Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/index-operations-v2/index-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/index-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'Partition Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/partition-operations-v2/partition-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/partition-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'Vector Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/vector-operations-v2/vector-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/vector-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'Alias Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/alias-operations-v2/alias-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/alias-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'Role Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/role-operations-v2/role-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/role-operations-v2" }] 
              },
              {
                type: 'category',
                label: 'User Operations',
                link: { type: 'doc', id: 'api/restful/restful/v2/data-plane/user-operations-v2/user-operations-v2' },
                collapsed: false,
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v2/data-plane/user-operations-v2" }] 
              }
            ]
          }
        ],
      },
      {
        type: 'category',
        label: 'V1',
        link: { type: 'doc', id: 'api/restful/restful/v1/v1' },
        collapsible: false,
        items: [
          {
            type: 'category',
            label: 'Control Plane',
            link: { type: 'doc', id: 'api/restful/restful/v1/control-plane/control-plane' },
            items: [
              {
                type: 'category',
                label: 'Cloud Meta',
                link: { type: 'doc', id: 'api/restful/restful/v1/control-plane/cloud-meta/cloud-meta' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/control-plane/cloud-meta" }]
              },
              {
                type: 'category',
                label: 'Cluster Operations',
                link: { type: 'doc', id: 'api/restful/restful/v1/control-plane/cluster-operations/cluster-operations' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/control-plane/cluster-operations" }]
              },
              {
                type: 'category',
                label: 'Import Operations',
                link: { type: 'doc', id: 'api/restful/restful/v1/control-plane/import-operations/import-operations' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/control-plane/import-operations" }]
              },
              {
                type: 'category',
                label: 'Pipeline Operations',
                link: { type: 'doc', id: 'api/restful/restful/v1/control-plane/pipeline-operations/pipeline-operations' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/control-plane/pipeline-operations" }]
              }
            ]
          },
          {
            type: 'category',
            label: 'Data Plane',
            link: { type: 'doc', id: 'api/restful/restful/v1/data-plane/data-plane' },
            items: [
              {
                type: 'category',
                label: 'Collection Operations',
                link: { type: 'doc', id: 'api/restful/restful/v1/data-plane/collection-operations/collection-operations' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/data-plane/collection-operations" }] 
              },
              {
                type: 'category',
                label: 'Vector Operations',
                link: { type: 'doc', id: 'api/restful/restful/v1/data-plane/vector-operations/vector-operations' },
                items: [{ type: "autogenerated", dirName: "api/restful/restful/v1/data-plane/vector-operations" }] 
              }
            ]
          }
        ],
      },
      'api/restful/restful/error-codes'
    ],
    pythonSidebar: [{type: 'autogenerated', dirName: 'api/python'}],
    javaSidebar: [{type: 'autogenerated', dirName: 'api/java'}],
    goSidebar: [{type: 'autogenerated', dirName: 'api/go'}],
    nodeSidebar: [{type: 'autogenerated', dirName: 'api/nodejs'}],
  
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
  };
  
  module.exports = sidebars;