/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Zilliz Cloud 开发指南",
  "tagline": "一次找全所有和 Zilliz Cloud 开发相关的文档",
  "favicon": "img/favicon.svg",
  "trailingSlash": false,
  "url": "https://docs.zilliz.com.cn",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/anthony/Documents/repos/zdoc_cn/sidebarsTutorial.js",
          "routeBasePath": "/"
        },
        "theme": {
          "customCss": "/Users/anthony/Documents/repos/zdoc_cn/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "reference",
        "path": "reference",
        "routeBasePath": "reference",
        "sidebarPath": "/Users/anthony/Documents/repos/zdoc_cn/sidebarsReference.js"
      }
    ],
    [
      "docusaurus-gtm-plugin",
      {
        "id": "GTM-MBBF2KR"
      }
    ],
    "./plugins/lark-docs",
    "./plugins/apifox-docs",
    "./plugins/landing-page",
    "./plugins/github-code"
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Zilliz Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "/",
          "label": "开发指南",
          "position": "left",
          "className": "header-link"
        },
        {
          "href": "/reference",
          "label": "API 参考",
          "position": "left",
          "className": "header-link"
        },
        {
          "href": "https://zilliz.com.cn",
          "label": "产品",
          "position": "left",
          "className": "header-link"
        },
        {
          "href": "https://zilliz.com.cn/pricing",
          "label": "定价",
          "position": "left",
          "className": "header-link"
        },
        {
          "type": "dropdown",
          "label": "资源中心",
          "position": "left",
          "items": [
            {
              "label": "博客",
              "href": "https://zilliz.com.cn/blog"
            },
            {
              "label": "白皮书",
              "href": "https://zilliz.com.cn/resources?tag=whitepapers"
            },
            {
              "label": "线上直播",
              "href": "https://zilliz.com.cn/resources?tag=live"
            },
            {
              "label": "活动",
              "href": "https://zilliz.com.cn/event"
            }
          ]
        },
        {
          "href": "https://zilliz.com.cn/use-cases",
          "label": "场景解决方案",
          "position": "left",
          "className": "header-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "logo": {
        "alt": "Zilliz",
        "src": "/img/logo.svg",
        "href": "https://zilliz.com",
        "width": 160,
        "height": 51
      },
      "links": [
        {
          "title": "文档",
          "items": [
            {
              "label": "开发指南",
              "to": "/"
            },
            {
              "label": "API 参考",
              "to": "/reference"
            }
          ]
        },
        {
          "title": "产品",
          "items": [
            {
              "label": "Zilliz Cloud",
              "href": "https://zilliz.com.cn/cloud"
            }
          ]
        },
        {
          "title": "关注我们",
          "items": [
            {
              "label": "Bilibili",
              "href": "https://space.bilibili.com/1058892339/video"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/zilliztech"
            }
          ]
        },
        {
          "title": "其它",
          "items": [
            {
              "label": "博客",
              "to": "https://zilliz.com.cn/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "LF AI、LF AI & Data、Milvus，以及相关的开源项目名称为 Linux Foundation 所有商标 <br/>版权所有 ©2023 上海赜睿信息科技有限公司保留所有权利。<br/>ICP 备案: 沪ICP备2023014543号<br/><a class=\"setting-cookie-btn\" >Cookie 设置</a>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "go"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "light",
      "respectPrefersColorScheme": false
    },
    "hotjar": {
      "applicationId": 3711906
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "themes": [
    [
      "/Users/anthony/Documents/repos/zdoc_cn/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexBlog": false,
        "language": [
          "en",
          "zh"
        ],
        "docsDir": [
          "docs",
          "reference"
        ],
        "docsRouteBasePath": [
          "/",
          "/docs/tutorials",
          "/reference/api"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "searchContextByPaths": [
          "/",
          "/docs/tutorials",
          "/reference/api"
        ]
      }
    ],
    "docusaurus-theme-frontmatter"
  ],
  "scripts": [
    {
      "src": "/js/cookieconsent.js",
      "async": true
    },
    "/js/zilliz.js"
  ],
  "stylesheets": [
    "/css/cookieconsent.css"
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
