name: "fetch lark docs (manual)"
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: fetch docs
      run: |
        yarn
        npx docusaurus report-to-lark -m "🔥 开始构建中文用户指南..."
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.saas -oss
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.saas -post
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.paas -oss -skipS
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.paas -post
        npx docusaurus fetch-lark-docs -man onpremise -tar paas -oss
        npx docusaurus fetch-lark-docs -man onpremise -tar paas -post
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_ENDPOINT: ${{ vars.OSS_ENDPOINT }}
        OSS_BUCKET: ${{ vars.OSS_BUCKET }}
        OSS_REGION: ${{ vars.OSS_REGION }}
        IMAGE_BED_URL: ${{ vars.IMAGE_BED_URL }}
    - name: build docsite
      run: |
        npx docusaurus report-to-lark -m "🔥 用户指南已成功获取！开始构建文档站点..."
        npm run build
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
    - name: check links
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
      run: |
        npx docusaurus report-to-lark -m "🔥 用户构建成功！开始检查链接..."
        npx docusaurus link-checks
    - name: commit to dev
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: dev
        create_branch: true
        push_options: --force
    - name: fetch sdk references
      id: fetch_sdk_refs
      run: |
        npx docusaurus report-to-lark -m "🔥 获取中文参考文档..."
        npx docusaurus fetch-lark-docs -man python -src-only
        npx docusaurus fetch-lark-docs -man pymilvus25 -src-only
        npx docusaurus fetch-lark-docs -man pymilvus26 -tar zilliz -oss
        npx docusaurus fetch-lark-docs -man pymilvus26 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man javaV2 -src-only
        npx docusaurus fetch-lark-docs -man javaV225 -src-only
        npx docusaurus fetch-lark-docs -man javaV226 -tar zilliz -oss
        npx docusaurus fetch-lark-docs -man javaV226 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man node -src-only
        npx docusaurus fetch-lark-docs -man nodejs25 -src-only
        npx docusaurus fetch-lark-docs -man nodejs26 -tar zilliz -oss
        npx docusaurus fetch-lark-docs -man nodejs26 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man gov2 -src-only
        npx docusaurus fetch-lark-docs -man gov226 -tar zilliz -oss
        npx docusaurus fetch-lark-docs -man gov226 -tar zilliz -post
        npx docusaurus fetch-apifox-docs -s plugins/apifox-docs/meta/openapi.json -l zh-CN  
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_ENDPOINT: ${{ vars.OSS_ENDPOINT }}
        OSS_BUCKET: ${{ vars.OSS_BUCKET }}
        OSS_REGION: ${{ vars.OSS_REGION }}
        IMAGE_BED_URL: ${{ vars.IMAGE_BED_URL }}
    - name: build docsite
      run: |
        npx docusaurus report-to-lark -m "🔥 参考文档已成功获取！开始构建文档站点..."
        npm run build
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
    - name: link checks
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
      run: |
        npx docusaurus report-to-lark -m "🔥 文档站点构建成功！开始检查链接..."
        npx docusaurus link-checks
    - name: commit to dev
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: dev
        create_branch: true
        push_options: --force
  failure:
    needs: fetch
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: report failure
      run : |
        yarn
        npx docusaurus report-to-lark -m "🔥 构建失败！请检查日志。"
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
  success:
    needs: fetch
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: report success
      run : |
        yarn
        npx docusaurus report-to-lark -m "🔥 构建成功！可以前往 Jenkins 进行正式构建！"
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}    
